namespace Solar.Models;

/// <summary>
/// Consolidated monthly energy and grid reliability statistics aggregated from daily metrics.
/// </summary>
public class MonthlyEnergyMetricDto
{
    /// <summary>
    /// Identifier of the inverter device.
    /// </summary>
    public string DeviceId { get; set; } = string.Empty;

    /// <summary>
    /// Calendar year (e.g. 2026).
    /// </summary>
    public int Year { get; set; }

    /// <summary>
    /// Calendar month (1-12).
    /// </summary>
    public int Month { get; set; }

    /// <summary>
    /// Human-readable month label (e.g. "September 2026").
    /// </summary>
    public string MonthName { get; set; } = string.Empty;

    /// <summary>
    /// Overall electricity consumed by loads during this month in kilowatt-hours (kWh).
    /// </summary>
    public double TotalLoadEnergyKwh { get; set; }

    /// <summary>
    /// Electricity drawn exclusively from the public utility grid in kilowatt-hours (kWh).
    /// </summary>
    public double GridImportEnergyKwh { get; set; }

    /// <summary>
    /// Electricity generated by the solar photovoltaic array in kilowatt-hours (kWh).
    /// </summary>
    public double PvGenerationEnergyKwh { get; set; }

    /// <summary>
    /// Total duration the utility grid was actively available in hours.
    /// </summary>
    public double GridUptimeHours { get; set; }

    /// <summary>
    /// Total duration the utility grid was absent or out of tolerance in hours.
    /// </summary>
    public double GridOutageHours { get; set; }

    /// <summary>
    /// Percentage of time the public utility grid was available during this month (0-100%).
    /// </summary>
    public double GridAvailabilityPercentage { get; set; }

    /// <summary>
    /// Number of calendar days with recorded telemetry for this month.
    /// </summary>
    public int DaysRecorded { get; set; }

    /// <summary>
    /// Average daily electricity consumed by loads in kilowatt-hours (kWh/day).
    /// </summary>
    public double AverageDailyLoadKwh { get; set; }

    /// <summary>
    /// Average daily solar generation in kilowatt-hours (kWh/day).
    /// </summary>
    public double AverageDailyPvKwh { get; set; }
}
