using System;

namespace Solar.Entities;

/// <summary>
/// Consolidated daily energy and grid reliability statistics for research and analysis.
/// </summary>
public class DailyEnergyMetric
{
    public long Id { get; set; }

    /// <summary>
    /// Identifier of the inverter device.
    /// </summary>
    public string DeviceId { get; set; } = string.Empty;

    /// <summary>
    /// Calendar date of the metric (station local date).
    /// </summary>
    public DateOnly Date { get; set; }

    /// <summary>
    /// Overall electricity consumed by the household loads in kilowatt-hours (kWh).
    /// </summary>
    public double TotalLoadEnergyKwh { get; set; }

    /// <summary>
    /// Electricity drawn exclusively from the public utility grid in kilowatt-hours (kWh).
    /// </summary>
    public double GridImportEnergyKwh { get; set; }

    /// <summary>
    /// Electricity generated by the solar photovoltaic array in kilowatt-hours (kWh).
    /// </summary>
    public double PvGenerationEnergyKwh { get; set; }

    /// <summary>
    /// Total duration the public utility grid was actively connected and available in hours.
    /// Derived from telemetry intervals where AcInputVoltage > 50V.
    /// </summary>
    public double GridUptimeHours { get; set; }

    /// <summary>
    /// Total duration the public utility grid was absent or out of tolerance in hours.
    /// </summary>
    public double GridOutageHours { get; set; }

    /// <summary>
    /// Number of telemetry samples processed and consolidated for this day.
    /// </summary>
    public int TelemetrySampleCount { get; set; }

    /// <summary>
    /// Timestamp when this daily summary was last computed or updated (UTC).
    /// </summary>
    public DateTimeOffset LastCalculatedAtUtc { get; set; } = DateTimeOffset.UtcNow;
}
