// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Solar.Data;

#nullable disable

namespace Solar.Migrations
{
    [DbContext(typeof(SolarDbContext))]
    partial class SolarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Solar.Entities.DailyEnergyMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<double>("GridImportEnergyKwh")
                        .HasColumnType("float");

                    b.Property<double>("GridOutageHours")
                        .HasColumnType("float");

                    b.Property<double>("GridUptimeHours")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("LastCalculatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("PvGenerationEnergyKwh")
                        .HasColumnType("float");

                    b.Property<int>("TelemetrySampleCount")
                        .HasColumnType("int");

                    b.Property<double>("TotalLoadEnergyKwh")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_DailyEnergyMetrics_DeviceId_Date");

                    b.ToTable("DailyEnergyMetrics", (string)null);
                });

            modelBuilder.Entity("Solar.Entities.InverterReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("AcInputVoltage")
                        .HasColumnType("float");

                    b.Property<double?>("BatterySoc")
                        .HasColumnType("float");

                    b.Property<double?>("BatteryVoltage")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<double>("GridPowerWatts")
                        .HasColumnType("float");

                    b.Property<bool>("IsGridAvailable")
                        .HasColumnType("bit");

                    b.Property<double>("LoadPowerWatts")
                        .HasColumnType("float");

                    b.Property<string>("OperatingMode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<double>("PvPowerWatts")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_InverterReadings_Timestamp");

                    b.HasIndex("DeviceId", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("IX_InverterReadings_DeviceId_Timestamp");

                    b.ToTable("InverterReadings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
